services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django-web:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000" ]

  celery-worker:
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
      - django-web
    volumes:
      - .:/app
    command: ["celery", "-A", "asphalt_aid", "worker", "--loglevel=info"]
