# Generated by Django 5.1.7 on 2025-05-23 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low - Minor issue'), (2, 'Low-Medium'), (3, 'Medium'), (4, 'Medium-High'), (5, 'High - Urgent attention needed')], default=3, help_text='Severity level determined by AI analysis of the uploaded image', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
