# Generated by Django 5.1.7 on 2025-05-23 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_alter_report_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.IntegerField(choices=[(0, 'No severity - Normal road'), (1, 'Low - Minor issue'), (2, 'Medium - Moderate damage'), (3, 'High - Major damage')], default=1, help_text='Severity level determined by AI analysis of the uploaded image (0-3 scale)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
