# Generated by Django 5.1.7 on 2025-05-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0003_alter_report_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
